micronaut:
  application:
    name: rag-dealer

gigachat:
  api:
    base-url: https://gigachat.devices.sberbank.ru/api/v1
    model-id: ${GIGACHAT_MODEL_ID:GigaChat-2-Max}
  oauth:
    base-url: https://ngw.devices.sberbank.ru:9443/api/v2/oauth
    scope: ${GIGACHAT_SCOPE:GIGACHAT_API_PERS}
    client-id: ${GIGACHAT_CLIENT_ID:CHANGEME}
    client-secret: ${GIGACHAT_CLIENT_SECRET:CHANGEME}
  token:
    proactive-refresh-seconds: 60
